version: "3.7"

services:

  weather:
    build: .
    command: python3 /usr/app/weather.py
    volumes:
      - /srv/docker/prefect/flows:/flows
      - ./app:/usr/app:ro
    environment:
      PREFECT_API_URL: "http://172.17.0.1:4200/api"
