version: "3.7"

services:

  agent:
    build: .
    privileged: true # forced for Docker DinD
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        docker login -u=myusername -p=test http://172.17.0.1:5000 
        mkdir -p /opt/prefect/flows
        prefect agent start --work-queue flows-example-queue-docker
    environment:
      PREFECT_API_URL: "http://172.17.0.1:4200/api"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
